version: "3.8"
services:
  api-gateway:
    container_name: api-gateway-service
    build:
      context: backend/api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
  auth:
    container_name: auth-service
    build:
      context: backend/auth-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
    networks:
      - app-network
  chat:
    container_name: chat-service
    build:
      context: backend/chat-service
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      cassandra:
        condition: service_healthy
    networks:
      - app-network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: "MyCluster"
      CASSANDRA_DC: "datacenter1"
      CASSANDRA_RACK: "rack1"
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
    networks:
      - app-network
    volumes:
      - cassandra-data:/var/lib/cassandra
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 10s
      timeout: 5s
      retries: 10
  front:
    container_name: front-end
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # prevent node_modules from being overwritten
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  cassandra-data:
