server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalCors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**, /oauth2/**, /login/**
        - id: chat-service
          uri: http://chat-service:8082
          predicates:
            - Path=/api/**
        - id: profile-service
          uri: http://profile-service:8083
          predicates:
            - Path=/profile/**
