spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: chat-service
  ai:
    ollama:
      base-url: http://ollama-service:11434
      chat:
        options:
          model: tinyllama:1.1b
server:
  port: 8082